import '../models/models.dart';
import 'calculations.dart';

String generateShareText(Project project, ProjectBreakdown breakdown) {
  final buf = StringBuffer();
  final divider = '─' * 36;

  buf.writeln('ESTIMATE');
  buf.writeln('Project: ${project.name}');
  buf.writeln('Date: ${_fmtDate(project.createdAt)}');
  if (project.contact.isNotEmpty) buf.writeln('Contact: ${project.contact}');
  if (project.address.isNotEmpty) buf.writeln('Address: ${project.address}');
  buf.writeln();

  for (final room in breakdown.rooms) {
    buf.writeln(divider);
    buf.writeln(room.name.toUpperCase());
    buf.writeln(divider);

    if (room.laborLines.isNotEmpty) {
      buf.writeln('LABOR');
      for (final l in room.laborLines) {
        final diff = l.difficulty != null ? ' (${l.difficulty})' : '';
        buf.writeln('  ${l.label}$diff');
        buf.writeln('    ${l.qty} ${l.unit} × \$${l.rate.toStringAsFixed(2)} = \$${l.cost.toStringAsFixed(2)}');
      }
    }

    if (room.matLines.isNotEmpty) {
      buf.writeln('MATERIALS');
      for (final l in room.matLines) {
        buf.writeln('  ${l.label.padRight(30)} \$${l.cost.toStringAsFixed(2)}');
      }
    }

    buf.writeln('  Room Total: \$${room.total.toStringAsFixed(2)}');
    buf.writeln();
  }

  buf.writeln(divider);
  buf.writeln('Labor:     \$${breakdown.labor.toStringAsFixed(2)}');
  buf.writeln('Materials: \$${breakdown.materials.toStringAsFixed(2)}');
  buf.writeln(divider);
  buf.writeln('TOTAL ESTIMATE: \$${breakdown.total.toStringAsFixed(2)}');
  buf.writeln(divider);
  buf.writeln();
  buf.writeln('Generated by Elegant Tile Manager');

  return buf.toString();
}

String _fmtDate(DateTime d) =>
    '${d.month}/${d.day}/${d.year}';
